/**
 * Drizzle schema for the current MySQL database.
 */
import { mysqlTable, text, int, double, boolean, primaryKey, varchar } from 'drizzle-orm/mysql-core'

export const dramas = mysqlTable('dramas', {
  id: int('id').autoincrement().primaryKey(),
  userId: int('user_id'),
  title: text('title').notNull(),
  description: text('description'),
  genre: text('genre'),
  style: varchar('style', { length: 64 }).default('realistic'),
  totalEpisodes: int('total_episodes').default(1),
  totalDuration: int('total_duration').default(0),
  status: varchar('status', { length: 32 }).notNull().default('draft'),
  thumbnail: text('thumbnail'),
  tags: text('tags'),
  metadata: text('metadata'),
  imageConfigId: int('image_config_id'),
  videoConfigId: int('video_config_id'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})
export const episodes = mysqlTable('episodes', {
  id: int('id').autoincrement().primaryKey(),
  dramaId: int('drama_id').notNull(),
  episodeNumber: int('episode_number').notNull(),
  title: text('title').notNull(),
  content: text('content'),
  scriptContent: text('script_content'),
  description: text('description'),
  duration: int('duration').default(0),
  status: varchar('status', { length: 32 }).default('draft'),
  videoUrl: text('video_url'),
  thumbnail: text('thumbnail'),
  imageConfigId: int('image_config_id'),
  videoConfigId: int('video_config_id'),
  transitionType: varchar('transition_type', { length: 32 }),
  transitionDurationMs: int('transition_duration_ms'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
  automationStatus: varchar('automation_status', { length: 16 }).default('idle'),
  automationStage: varchar('automation_stage', { length: 32 }).default('extract'),
  automationAttempt: int('automation_attempt').default(0),
  automationError: text('automation_error'),
  automationStoryboardChunk: int('automation_storyboard_chunk').default(0),
})
export const characters = mysqlTable('characters', {
  id: int('id').autoincrement().primaryKey(),
  dramaId: int('drama_id').notNull(),
  name: text('name').notNull(),
  role: text('role'),
  description: text('description'),
  appearance: text('appearance'),
  personality: text('personality'),
  imagePrompt: text('image_prompt'),
  imageUrl: text('image_url'),
  referenceImages: text('reference_images'),
  characterAssetId: int('character_asset_id'),
  seedValue: text('seed_value'),
  sortOrder: int('sort_order'),
  localPath: text('local_path'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const characterAssets = mysqlTable('character_assets', {
  id: int('id').autoincrement().primaryKey(),
  userId: int('user_id'),
  name: text('name').notNull(),
  gender: varchar('gender', { length: 32 }).default('unknown'),
  rolePreset: varchar('role_preset', { length: 64 }).default('custom'),
  imageUrl: text('image_url').notNull(),
  localPath: text('local_path'),
  description: text('description'),
  appearance: text('appearance'),
  tags: text('tags'),
  isDefault: boolean('is_default').default(false),
  isActive: boolean('is_active').default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

// Episode-Character many-to-many
export const episodeCharacters = mysqlTable('episode_characters', {
  id: int('id').autoincrement().primaryKey(),
  episodeId: int('episode_id').notNull(),
  characterId: int('character_id').notNull(),
  createdAt: text('created_at').notNull(),
})

// Episode-Scene many-to-many
export const episodeScenes = mysqlTable('episode_scenes', {
  id: int('id').autoincrement().primaryKey(),
  episodeId: int('episode_id').notNull(),
  sceneId: int('scene_id').notNull(),
  createdAt: text('created_at').notNull(),
})

export const scenes = mysqlTable('scenes', {
  id: int('id').autoincrement().primaryKey(),
  dramaId: int('drama_id').notNull(),
  episodeId: int('episode_id'),
  location: text('location').notNull(),
  time: text('time').notNull(),
  prompt: text('prompt').notNull(),
  storyboardCount: int('storyboard_count').default(1),
  imageUrl: text('image_url'),
  referenceImage: text('reference_image'),
  status: varchar('status', { length: 32 }).default('pending'),
  localPath: text('local_path'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const storyboards = mysqlTable('storyboards', {
  id: int('id').autoincrement().primaryKey(),
  episodeId: int('episode_id').notNull(),
  sceneId: int('scene_id'),
  storyboardNumber: int('storyboard_number').notNull(),
  title: text('title'),
  location: text('location'),
  time: text('time'),
  shotType: text('shot_type'),
  angle: text('angle'),
  movement: text('movement'),
  action: text('action'),
  result: text('result'),
  atmosphere: text('atmosphere'),
  imagePrompt: text('image_prompt'),
  videoPrompt: text('video_prompt'),
  bgmPrompt: text('bgm_prompt'),
  soundEffect: text('sound_effect'),
  dialogue: text('dialogue'),
  description: text('description'),
  duration: int('duration').default(0),
  composedImage: text('composed_image'),
  firstFrameImage: text('first_frame_image'),
  lastFrameImage: text('last_frame_image'),
  referenceImages: text('reference_images'),
  videoUrl: text('video_url'),
  ttsAudioUrl: text('tts_audio_url'),
  subtitleUrl: text('subtitle_url'),
  composedVideoUrl: text('composed_video_url'),
  status: varchar('status', { length: 32 }).default('pending'),
  transitionType: varchar('transition_type', { length: 32 }),
  transitionDurationMs: int('transition_duration_ms'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const storyboardCharacters = mysqlTable('storyboard_characters', {
  storyboardId: int('storyboard_id').notNull(),
  characterId: int('character_id').notNull(),
}, (table) => ({
  pk: primaryKey({ columns: [table.storyboardId, table.characterId] }),
}))

export const aiServiceConfigs = mysqlTable('ai_service_configs', {
  id: int('id').autoincrement().primaryKey(),
  serviceType: text('service_type').notNull(),
  provider: text('provider'),
  name: text('name').notNull(),
  baseUrl: text('base_url').notNull(),
  apiKey: text('api_key').notNull(),
  model: text('model'),
  endpoint: text('endpoint'),
  queryEndpoint: text('query_endpoint'),
  priority: int('priority').default(0),
  isDefault: boolean('is_default').default(false),
  isActive: boolean('is_active').default(true),
  settings: text('settings'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  // 娉ㄦ剰: 姝よ〃鏃?deleted_at
})

export const aiServiceProviders = mysqlTable('ai_service_providers', {
  id: int('id').autoincrement().primaryKey(),
  name: text('name').notNull(),
  displayName: text('display_name'),
  serviceType: text('service_type').notNull(),
  provider: text('provider').notNull(),
  defaultUrl: text('default_url'),
  presetModels: text('preset_models'),
  description: text('description'),
  isActive: boolean('is_active').default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})

export const users = mysqlTable('users', {
  id: int('id').autoincrement().primaryKey(),
  username: varchar('username', { length: 64 }).notNull(),
  email: varchar('email', { length: 191 }).notNull(),
  phone: varchar('phone', { length: 32 }).notNull(),
  passwordHash: text('password_hash').notNull(),
  status: varchar('status', { length: 32 }).notNull().default('active'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  lastLoginAt: text('last_login_at'),
})

export const authSessions = mysqlTable('auth_sessions', {
  token: varchar('token', { length: 128 }).primaryKey(),
  userId: int('user_id').notNull(),
  expiresAt: text('expires_at').notNull(),
  createdAt: text('created_at').notNull(),
})

export const smsCodes = mysqlTable('sms_codes', {
  id: int('id').autoincrement().primaryKey(),
  phone: varchar('phone', { length: 32 }).notNull(),
  purpose: varchar('purpose', { length: 32 }).notNull().default('register'),
  codeHash: text('code_hash').notNull(),
  salt: varchar('salt', { length: 64 }).notNull(),
  expiresAt: text('expires_at').notNull(),
  usedAt: text('used_at'),
  attempts: int('attempts').notNull().default(0),
  createdAt: text('created_at').notNull(),
})

export const agentConfigs = mysqlTable('agent_configs', {
  id: int('id').autoincrement().primaryKey(),
  agentType: text('agent_type').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  model: text('model'),
  systemPrompt: text('system_prompt'),
  temperature: double('temperature'),
  maxTokens: int('max_tokens'),
  maxIterations: int('max_iterations'),
  isActive: boolean('is_active').default(true),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const imageGenerations = mysqlTable('image_generations', {
  id: int('id').autoincrement().primaryKey(),
  storyboardId: int('storyboard_id'),
  dramaId: int('drama_id'),
  sceneId: int('scene_id'),
  characterId: int('character_id'),
  propId: int('prop_id'),
  imageType: text('image_type'),
  frameType: text('frame_type'),
  provider: text('provider'),
  prompt: text('prompt'),
  negativePrompt: text('negative_prompt'),
  model: text('model'),
  size: text('size'),
  quality: text('quality'),
  style: text('style'),
  steps: int('steps'),
  cfgScale: double('cfg_scale'),
  seed: int('seed'),
  imageUrl: text('image_url'),
  minioUrl: text('minio_url'),
  localPath: text('local_path'),
  status: varchar('status', { length: 32 }).default('pending'),
  taskId: text('task_id'),
  errorMsg: text('error_msg'),
  width: int('width'),
  height: int('height'),
  referenceImages: text('reference_images'),
  normalizedRequest: text('normalized_request'),
  providerRequest: text('provider_request'),
  providerResponse: text('provider_response'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  completedAt: text('completed_at'),
})

export const videoGenerations = mysqlTable('video_generations', {
  id: int('id').autoincrement().primaryKey(),
  storyboardId: int('storyboard_id'),
  dramaId: int('drama_id'),
  provider: text('provider'),
  prompt: text('prompt'),
  model: text('model'),
  imageGenId: int('image_gen_id'),
  referenceMode: text('reference_mode'),
  imageUrl: text('image_url'),
  firstFrameUrl: text('first_frame_url'),
  lastFrameUrl: text('last_frame_url'),
  referenceImageUrls: text('reference_image_urls'),
  referenceVideoUrls: text('reference_video_urls'),
  referenceAudioUrls: text('reference_audio_urls'),
  duration: int('duration'),
  fps: int('fps'),
  resolution: text('resolution'),
  aspectRatio: text('aspect_ratio'),
  style: text('style'),
  motionLevel: int('motion_level'),
  cameraMotion: text('camera_motion'),
  seed: int('seed'),
  videoUrl: text('video_url'),
  minioUrl: text('minio_url'),
  localPath: text('local_path'),
  status: varchar('status', { length: 32 }).default('pending'),
  taskId: text('task_id'),
  errorMsg: text('error_msg'),
  width: int('width'),
  height: int('height'),
  normalizedRequest: text('normalized_request'),
  providerRequest: text('provider_request'),
  providerResponse: text('provider_response'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  completedAt: text('completed_at'),
  defectCheckAttempt: int('defect_check_attempt').default(0),
  defectCheckParentId: int('defect_check_parent_id'),
  defectCheckResult: text('defect_check_result'),
  tailFrameUrl: text('tail_frame_url'),
  deletedAt: text('deleted_at'),
})

export const videoMerges = mysqlTable('video_merges', {
  id: int('id').autoincrement().primaryKey(),
  episodeId: int('episode_id'),
  dramaId: int('drama_id'),
  title: text('title'),
  provider: text('provider'),
  model: text('model'),
  status: varchar('status', { length: 32 }).default('pending'),
  scenes: text('scenes'), // JSON
  mergedUrl: text('merged_url'),
  duration: int('duration'),
  taskId: text('task_id'),
  errorMsg: text('error_msg'),
  transitionType: varchar('transition_type', { length: 32 }),
  transitionDurationMs: int('transition_duration_ms'),
  claimedAt: varchar('claimed_at', { length: 32 }),
  createdAt: text('created_at').notNull(),
  completedAt: text('completed_at'),
  deletedAt: text('deleted_at'),
})

export const props = mysqlTable('props', {
  id: int('id').autoincrement().primaryKey(),
  dramaId: int('drama_id').notNull(),
  name: text('name').notNull(),
  type: text('type'),
  description: text('description'),
  prompt: text('prompt'),
  imageUrl: text('image_url'),
  referenceImages: text('reference_images'),
  localPath: text('local_path'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const assets = mysqlTable('assets', {
  id: int('id').autoincrement().primaryKey(),
  userId: int('user_id'),
  dramaId: int('drama_id'),
  episodeId: int('episode_id'),
  storyboardId: int('storyboard_id'),
  storyboardNum: int('storyboard_num'),
  name: text('name'),
  description: text('description'),
  type: text('type'),
  category: text('category'),
  url: text('url'),
  thumbnailUrl: text('thumbnail_url'),
  localPath: text('local_path'),
  fileSize: int('file_size'),
  mimeType: text('mime_type'),
  width: int('width'),
  height: int('height'),
  duration: int('duration'),
  format: text('format'),
  imageGenId: int('image_gen_id'),
  videoGenId: int('video_gen_id'),
  isFavorite: boolean('is_favorite').default(false),
  viewCount: int('view_count').default(0),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  deletedAt: text('deleted_at'),
})

export const userPreferences = mysqlTable('user_preferences', {
  userId: varchar('user_id', { length: 64 }).primaryKey(),
  autoPipelineEnabled: boolean('auto_pipeline_enabled').default(false),
  autoPipelineMaxRetries: int('auto_pipeline_max_retries').default(2),
  autoPipelineConcurrencyImage: int('auto_pipeline_concurrency_image').default(4),
  autoPipelineConcurrencyVideo: int('auto_pipeline_concurrency_video').default(2),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
})
